FROM epigramai/model-server:latest

COPY models/ models/

CMD ["serving/bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server", "--port=9000", "--model_name=mnist", "--model_base_path=models/mnist_cnn"]